### ISSUE TITLE
Wondering the equations of LSTM is correct

### ISSUE THREAD

**Issue by spk921** [jimfleming/lstm_search#2]
For vanilla LSTM equation
i = tf.sigmoid(tf.matmul(inputs, W_i) + tf.matmul(y_prev, R_i) + tf.mul(c_prev, p_i) + b_i) 
f = tf.sigmoid(tf.matmul(inputs, W_f) + tf.matmul(y_prev, R_f) + tf.mul(c_prev, p_f) + b_f) 

isn't it  this? Ref for equations : http://deeplearning.net/tutorial/lstm.html
i = tf.sigmoid(tf.matmul(inputs, W_i) + tf.matmul(y_prev, R_i) + b_i) 
f = tf.sigmoid(tf.matmul(inputs, W_f) + tf.matmul(y_prev, R_f)+ b_f)

**Comment by jimfleming** [comment]
We use the definition of "vanilla LSTM" from the paper [LSTM: A Search Space Odyssey](https://arxiv.org/abs/1503.04069) which includes "peephole" connections allowing the gates to peek at the previous cell state. These were added after the initial paper but fairly standard in LSTM implementations today.
